version: '3.1'

services:

  db:
    build:
      context: ./Docker
      dockerfile: db-dockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: portfolio
    ports:
      - 5432:5432